/**
 * timelineBuilder.ts — mission sections 15-18, Deep Domain File 3 §N.
 *
 * This is the load-bearing core of the whole engine. The authoritative
 * construction unit is the individual calendar date — never a month record,
 * never a week record, never a sparse "just the holidays/exams" list. Every
 * date from the academic year's start through its end exists exactly once,
 * generated by advancing one calendar day at a time, and independently
 * re-verified before this module will hand the result back to a caller.
 *
 * "Never publish an invalid timeline" is enforced structurally: there is no
 * code path in this file that returns a `DailyTimelineEntry[]` without first
 * passing it through `verifyTimelineIntegrity`.
 */
import { AppError } from '../errors/AppError'
import {
  differenceInCalendarDays,
  eachDayInclusive,
  isAfter,
  isSameOrAfter,
  isSameOrBefore,
  isWeekend,
  weekdayName,
} from './date-utils'
import type { ISODate } from './date-utils'
import { toEthiopian } from './ethiopian-date'
import { HOLIDAY_TYPES, indexHolidaysByDate } from './holidays'
import { EXAM_TYPES, indexExamsByDate } from './exams'
import type { TimelineExamHit } from './exams'
import { deriveSemesterBreak } from './semesterBreak'
import type { SemesterBreak } from './semesterBreak'
import type {
  CalendarConfiguration,
  DailyTimelineEntry,
  HolidayOccurrence,
  Semester,
  TimelineExamInfo,
  TimelineHolidayInfo,
} from './types'

function assertValidBoundary(start: ISODate, end: ISODate): void {
  if (isAfter(start, end)) {
    throw new AppError(
      'CALENDAR_INVALID_BOUNDARY',
      422,
      `Academic year start (${start}) is after its end (${end}).`,
    )
  }
}

interface DescribeDateContext {
  academicYearId: string
  semesters: Semester[]
  holidaysByDate: Map<ISODate, HolidayOccurrence[]>
  examsByDate: Map<ISODate, TimelineExamHit[]>
  studentReturnDate: ISODate | null
  semesterBreak: SemesterBreak | null
}

function semesterOrderForDate(date: ISODate, semesters: Semester[]): 1 | 2 | null {
  for (const s of semesters) {
    if (s.startDate && s.endDate && isSameOrAfter(date, s.startDate) && isSameOrBefore(date, s.endDate)) {
      return s.order
    }
  }
  return null
}

/**
 * Builds one date's complete state (mission section 18's checklist). Every
 * condition below only ever pushes `schoolOpen` / `teachingDay` /
 * `attendanceAvailable` from true toward false — never back — so the order
 * the checks run in doesn't matter for correctness, only for which reason
 * strings get recorded, and it can never double-subtract a day (mission
 * section 22: "one date, several reasons... it only gets removed once" is a
 * property of the *counting* step in teachingDays.ts, guaranteed here by
 * these being booleans, not counters).
 */
export function describeDate(date: ISODate, ctx: DescribeDateContext): DailyTimelineEntry {
  const ethiopian = toEthiopian(date)
  const weekday = weekdayName(date)
  const weekend = isWeekend(date)

  const holidayOccurrences = ctx.holidaysByDate.get(date) ?? []
  const holidays: TimelineHolidayInfo[] = holidayOccurrences.map((h) => ({
    typeKey: h.holidayTypeKey,
    name: HOLIDAY_TYPES[h.holidayTypeKey].name,
    closesSchool: h.closesSchool,
  }))
  const holidayClosure = holidays.some((h) => h.closesSchool)

  const examHits = ctx.examsByDate.get(date) ?? []
  const exams: TimelineExamInfo[] = examHits.map((hit) => ({
    typeKey: hit.examTypeKey,
    name: EXAM_TYPES[hit.examTypeKey].name,
    dayNumber: hit.dayNumber,
    totalDays: hit.totalDays,
    closesSchool: EXAM_TYPES[hit.examTypeKey].closesSchool,
    gradeScope: EXAM_TYPES[hit.examTypeKey].gradeScope,
  }))
  const examClosure = exams.some((e) => e.closesSchool)

  const isStudentReturn = ctx.studentReturnDate === date
  const isSemesterBreak =
    !!ctx.semesterBreak &&
    isSameOrAfter(date, ctx.semesterBreak.startDate) &&
    isSameOrBefore(date, ctx.semesterBreak.endDate)

  const reasons: string[] = []
  let schoolOpen = true
  let teachingDay = true
  let attendanceAvailable = true

  if (weekend) {
    reasons.push('WEEKEND')
    schoolOpen = false
    teachingDay = false
    attendanceAvailable = false
  }
  // Fix #9: one reason string per closing holiday — every configured fact
  // stays visible in `reasons` even though schoolOpen/teachingDay/
  // attendanceAvailable are only ever pushed false once, not once per
  // holiday (mission section 22's "removed from the count exactly once").
  for (const h of holidays) {
    if (h.closesSchool) reasons.push(`HOLIDAY_CLOSURE:${h.typeKey}`)
  }
  if (holidayClosure) {
    schoolOpen = false
    teachingDay = false
    attendanceAvailable = false
  }
  if (isSemesterBreak) {
    reasons.push('SEMESTER_BREAK')
    schoolOpen = false
    teachingDay = false
    attendanceAvailable = false
  }
  if (isStudentReturn) {
    reasons.push('STUDENT_RETURN')
    teachingDay = false
    attendanceAvailable = false
    // schoolOpen deliberately untouched: Student Return is open, non-teaching
    // (mission section 21 — "a date can be school open but non-teaching").
  }
  for (const e of exams) {
    reasons.push(e.closesSchool ? `EXAM_CLOSURE:${e.typeKey}` : `EXAM_PRESENT:${e.typeKey}`)
  }
  if (examClosure) {
    schoolOpen = false
    teachingDay = false
    attendanceAvailable = false
  }

  // Grade-12-specific suppression: any exam on this date with GRADE_12
  // scope suppresses grade12AttendanceAvailable, independent of whichever
  // OTHER exam (or nothing) also occupies the date — this is exactly the
  // "additional, narrower fact sitting alongside" the whole-school answer
  // that Deep Domain File 3 §N describes, which is why exams being an
  // array rather than a single value matters here specifically.
  let grade12AttendanceAvailable = attendanceAvailable
  for (const e of exams) {
    if (e.gradeScope === 'GRADE_12' && grade12AttendanceAvailable) {
      grade12AttendanceAvailable = false
      reasons.push(`GRADE12_ATTENDANCE_SUPPRESSED:${e.typeKey}`)
    }
  }

  return {
    date,
    ethiopian,
    weekday,
    isWeekend: weekend,
    academicYearId: ctx.academicYearId,
    semesterOrder: semesterOrderForDate(date, ctx.semesters),
    holidays,
    holidayClosure,
    exams,
    isStudentReturn,
    isSemesterBreak,
    schoolOpen,
    teachingDay,
    attendanceAvailable,
    grade12AttendanceAvailable,
    reasons,
  }
}

export interface TimelineIntegrityReport {
  valid: boolean
  issues: string[]
  actualCount: number
  expectedCount: number
}

/**
 * The independent re-check mission section 16 Step 4 requires: re-derives
 * count/first/last/uniqueness/adjacency straight from the generated array
 * rather than trusting the generator that produced it. A generated timeline
 * that fails any condition here is invalid and must never be published.
 */
export function verifyTimelineIntegrity(
  entries: DailyTimelineEntry[],
  expectedStart: ISODate,
  expectedEnd: ISODate,
  expectedDays: number,
): TimelineIntegrityReport {
  const issues: string[] = []

  if (entries.length !== expectedDays) {
    issues.push(`Generated ${entries.length} entries; expected exactly ${expectedDays}.`)
  }

  const first = entries[0]
  const last = entries[entries.length - 1]
  if (!first || first.date !== expectedStart) {
    issues.push(`First entry is ${first?.date ?? '(none)'}, expected ${expectedStart}.`)
  }
  if (!last || last.date !== expectedEnd) {
    issues.push(`Last entry is ${last?.date ?? '(none)'}, expected ${expectedEnd}.`)
  }

  const seen = new Set<string>()
  let duplicates = 0
  for (const entry of entries) {
    if (seen.has(entry.date)) duplicates++
    seen.add(entry.date)
  }
  if (duplicates > 0) {
    issues.push(`${duplicates} duplicate date(s) found.`)
  }

  for (let i = 1; i < entries.length; i++) {
    const prev = entries[i - 1]
    const cur = entries[i]
    if (!prev || !cur) continue
    const gap = differenceInCalendarDays(cur.date, prev.date)
    if (gap !== 1) {
      issues.push(`Gap or overlap between index ${i - 1} (${prev.date}) and ${i} (${cur.date}): ${gap} day(s) apart.`)
    }
  }

  return { valid: issues.length === 0, issues, actualCount: entries.length, expectedCount: expectedDays }
}

/**
 * Builds the complete, deterministic full-year daily timeline for one
 * academic year's resolved configuration (mission section 16, Steps 1-4).
 * Throws `CALENDAR_TIMELINE_INTEGRITY_FAILURE` rather than ever returning
 * an invalid result — this function's return type is the caller's guarantee
 * that what they received is safe to publish as a candidate build.
 */
export function buildFullYearTimeline(config: CalendarConfiguration): DailyTimelineEntry[] {
  const { academicYear, semesters, holidayOccurrences, examInstances, studentReturn } = config
  assertValidBoundary(academicYear.startDate, academicYear.endDate)

  const expectedDays = differenceInCalendarDays(academicYear.endDate, academicYear.startDate) + 1

  const ctx: DescribeDateContext = {
    academicYearId: academicYear.id,
    semesters,
    holidaysByDate: indexHolidaysByDate(holidayOccurrences),
    examsByDate: indexExamsByDate(examInstances),
    studentReturnDate: studentReturn?.date ?? null,
    semesterBreak: deriveSemesterBreak(semesters),
  }

  const entries: DailyTimelineEntry[] = []
  for (const date of eachDayInclusive(academicYear.startDate, academicYear.endDate)) {
    entries.push(describeDate(date, ctx))
  }

  const report = verifyTimelineIntegrity(entries, academicYear.startDate, academicYear.endDate, expectedDays)
  if (!report.valid) {
    throw new AppError(
      'CALENDAR_TIMELINE_INTEGRITY_FAILURE',
      500,
      'Generated timeline failed integrity verification; it was not published.',
      report,
    )
  }

  return entries
}
